### ISSUE TITLE
Suggestion for autorelease

### ISSUE THREAD

**Issue by xandymp** [dracoapi/dracowalker#36]
The autorelease could have parameter on the config file like:

autorelease:
  mincp: 500
  healthIV: 5
  streghtIV: 5

I think it would work better if we could choose how to release the creatures.

**Comment by niicojs** [comment]
here is hat you can currently do with dev version:
```
behavior:
  autorelease:
      keepone: true
      mincp: 500
      minattack: 4
      minstamina: 4
```

`keepone` allows you to keep at least one of each type
