### ISSUE TITLE
clean inventory error ?

### ISSUE THREAD

**Issue by nocomp** [dracoapi/dracowalker#40]
hi,
i am having massive logs in windows version:

09:30:02 - info: Clean inventory
09:30:03 - info: Clean inventory
09:30:04 - info: Clean inventory
09:30:05 - info: Clean inventory
09:30:06 - info: Clean inventory
09:30:07 - info: Clean inventory
09:30:08 - info: Clean inventory
09:30:09 - warn: Unhandled object in map update: FMentorshipAwardUpdate
09:30:10 - info: Clean inventory
09:30:11 - info: Clean inventory

inventory is not full 230/250 no more catch or pokestop harvest, any ideas what is wrong?

**Comment by niicojs** [comment]
When inventory is becoming full (90% if I remember), auto clean kicks in, but you have to configure it.
Something like:
```
inventory:
  MAGIC_BALL_SIMPLE:   0 # apprentice sphere
  MAGIC_BALL_NORMAL:  30 # master sphere
  MAGIC_BALL_GOOD:    50 # ruler's sphere
  POTION_HEAL_1:  5 #
  POTION_HEAL_2: 10
  POTION_RESURRECTION_1: 20 # resurecting potion
  RUNE_1: 10
  RUNE_2: 10
  RUNE_3: 10
  FOOD_CATCH_CHANCE: 10   # arcana caramel
  FOOD_MORE_DUST: 10      # donut
  FOOD_CALM_DOWN: 10      # Marshmallow
  FOOD_MORE_CANDIES: 10   # ice-cream
```
